modLoader = "javafml"
loaderVersion = "[${forge_maj_version},)"
issueTrackerURL = "https://github.com/Infinituum17/LabellingContainers/issues"
license = "Infinituum License"

[[mods]]
modId = "${modid}"
version = "${version}"
displayName = "Labelling Containers"
authors = "Infinituum"
description = '''
This mod helps you organize the content of your chests and other containers by assigning them a name, and without using annoying signs
'''
logoFile = "assets/${modid}/icon.png"

[[dependencies.${ modid }]]
modId = "forge"
mandatory = true
versionRange = "[${forge_maj_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modid }]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modid }]]
modId = "architectury"
mandatory = true
versionRange = "[${arch_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ modid }]]
modId = "fastconfigapi"
mandatory = true
versionRange = "[${fastconfigapi_version},)"
ordering = "AFTER"
side = "BOTH"