modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Infinituum17/LabellingContainers/issues"
license = "MIT"

[[mods]]
modId = "${modid}"
version = "${version}"
displayName = "Labelling Containers"
authors = "Infinituum"
description = '''
This mod helps you organize the content of your chests and other containers by assigning them a name, and without using annoying signs
'''
logoFile = "assets/${modid}/icon.png"

[[dependencies.${ modid }]]
modId = "neoforge"
type="required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modid }]]
modId = "minecraft"
type="required"
versionRange = "[${mc_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modid }]]
modId = "architectury"
type="required"
versionRange = "[${arch_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ modid }]]
modId = "fastconfigapi"
type = "required"
versionRange = "[${fastconfigapi_version}]"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "external.mixins.json"

[[mixins]]
config = "labellingcontainers-common.mixins.json"